//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFKSpaceShips
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class SecureCoreG1Entities : DbContext
    {
        public SecureCoreG1Entities()
            : base("name=SecureCoreG1Entities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<SpaceShipCategories> SpaceShipCategories { get; set; }
        public virtual DbSet<SpaceShipTypes> SpaceShipTypes { get; set; }
    }
}
