//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FormFactories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Factories
    {
        public short idFactory { get; set; }
        public string codeFactory { get; set; }
        public string DescFactory { get; set; }
    }
}
